import { contractMeta, type AgreementType } from '@/lib/legal/contracts';

function escapePdfText(value: string) {
  return value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function buildSimplePdf(lines: string[]) {
  const content = ['BT', '/F1 11 Tf', '40 790 Td', '14 TL'];
  lines.forEach((line, index) => {
    const safe = escapePdfText(line || ' ');
    content.push(index === 0 ? `(${safe}) Tj` : `T* (${safe}) Tj`);
  });
  content.push('ET');
  const stream = content.join('\n');

  const objects = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj',
    '2 0 obj\n<< /Type /Pages /Count 1 /Kids [3 0 R] >>\nendobj',
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj',
    `4 0 obj\n<< /Length ${stream.length} >>\nstream\n${stream}\nendstream\nendobj`,
    '5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj',
  ];

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  for (const obj of objects) {
    offsets.push(pdf.length);
    pdf += `${obj}\n`;
  }
  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  for (let i = 1; i < offsets.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return pdf;
}

export function buildSimpleContractPdfString(agreementType: AgreementType) {
  const meta = contractMeta[agreementType];
  const title = agreementType === 'merchant' ? 'Affilia Merchant Agreement' : 'Affilia Affiliate Agreement';
  const lines = [
    title,
    'Bridge. Earn. Grow.',
    ' ',
    meta.blurb,
    ' ',
    'Key Summary',
    ...meta.summary.map((item) => `- ${item}`),
    ' ',
    'Core Clauses',
    ...meta.clauses.flatMap((clause) => [clause.heading, clause.detail, ' ']),
    'Required Acknowledgements',
    ...meta.acknowledgements.map((item) => `- ${item.label}`),
    ' ',
    'Generated by Affilia fallback PDF renderer.',
  ];
  return buildSimplePdf(lines);
}

export function buildSimpleContractPdfBlob(agreementType: AgreementType) {
  return new Blob([buildSimpleContractPdfString(agreementType)], { type: 'application/pdf' });
}

export function buildSimpleContractPdfBuffer(agreementType: AgreementType) {
  return Buffer.from(buildSimpleContractPdfString(agreementType), 'utf-8');
}
