name: CI Admin
on:
  push:
    paths:
      - 'apps/admin/**'
      - 'packages/**'
      - '.github/workflows/ci-admin.yml'
  pull_request:
    paths:
      - 'apps/admin/**'
      - 'packages/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter ./apps/admin lint
      - run: pnpm --filter ./apps/admin build
